# Quarkus Configuration
quarkus.application.name=backend
quarkus.package.type=uber-jar

# Amazon Services
quarkus.dynamodb.aws.region=us-east-1
quarkus.s3.aws.region=us-east-1

# Application Resource Names
app.dynamodb.table-messages=${MESSAGES_TABLE_NAME:Messages}
app.dynamodb.table-connections=${CONNECTIONS_TABLE_NAME:Connections}
app.s3.bucket-name=${STORAGE_BUCKET_NAME:push-bolt-storage}

# Lambda Configuration - Removing it breaks the building of multiple handlers
quarkus.lambda.handler=create-message


# Test Configuration
quarkus.http.test-port=0
%test.quarkus.devservices.enabled=false
